import os
import argparse
import pandas as pd
from datetime import date

GENOMES_DIR = os.path.join("data", "new_genomes")
REPORTS_DIR = os.path.join("results", "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

COLD  = "#1a5276"
BLUE  = "#2e86c1"
LIGHT = "#d6eaf8"
GREEN = "#1e8449"
WARN  = "#d35400"
GREY  = "#aab7b8"
WHITE = "#ffffff"


def interpret_ppi(ppi):
    if ppi > 50:
        return "PSYCHROPHILE / COLD EXTREMOPHILE", "Strong cold-adaptation signals detected across the proteome.", GREEN
    elif ppi > 30:
        return "PSYCHROTROPH / COLD-TOLERANT", "Moderate cold-adaptation signals. Grows in cold but prefers moderate temperatures.", WARN
    else:
        return "MESOPHILE", "Minimal cold-adaptation signal. Optimally adapted to moderate temperatures.", "#c0392b"


def load_results(organism):
    path = os.path.join(GENOMES_DIR, f"{organism}_full_results.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Not found: {path}\nRun: python src/09_predict_new_genome.py")
    return pd.read_csv(path)


def confidence_bar(prob, width=20):
    filled = int(prob * width)
    return "█" * filled + "░" * (width - filled)


# ── Markdown ──────────────────────────────────────────────────────────────────
def build_markdown(organism, df):
    top15      = df.nlargest(15, 'Cold_Probability')
    ppi        = df['Cold_Probability'].nlargest(100).mean() * 100
    frac_90    = (df['Cold_Probability'] >= 0.90).mean() * 100
    n_high     = (df['Cold_Probability'] >= 0.90).sum()
    verdict, desc, _ = interpret_ppi(ppi)
    org_display = organism.replace('_', ' ')

    lines = [
        f"# PsychroScan Report — *{org_display}*",
        f"",
        f"**Date:** {date.today()}   |   **Proteins analysed:** {len(df):,}   |   **Pipeline:** PsychroScan v3",
        f"",
        f"---",
        f"",
        f"## Verdict",
        f"",
        f"> ### {verdict}",
        f"> {desc}",
        f"",
        f"## Psychrophilic Proteome Index (PPI)",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| **PPI score** | **{ppi:.1f} / 100** |",
        f"| Top-100 mean probability | {df['Cold_Probability'].nlargest(100).mean()*100:.1f}% |",
        f"| Fraction above 90% confidence | {frac_90:.1f}% ({n_high:,} proteins) |",
        f"| Total proteins scored | {len(df):,} |",
        f"",
        f"PPI interpretation: **>50** = psychrophile · **30–50** = psychrotroph · **<30** = mesophile",
        f"",
        f"---",
        f"",
        f"## Top 15 Cold-Active Candidates",
        f"",
        f"| Rank | Protein ID | P(Cold) | Confidence |",
        f"|---|---|---|---|",
    ]
    for i, (_, row) in enumerate(top15.iterrows(), 1):
        p = row['Cold_Probability']
        bar = confidence_bar(p, 15)
        lines.append(f"| {i} | `{row['Protein_ID']}` | {p*100:.2f}% | `{bar}` |")

    lines += [
        f"",
        f"> Search any Protein ID at [UniProt](https://www.uniprot.org/uniprotkb/) for functional annotation.",
        f"",
        f"---",
        f"",
        f"## Score distribution",
        f"",
        f"| Percentile | Min P(Cold) to qualify |",
        f"|---|---|",
    ]
    for pct in [99, 95, 90, 75, 50]:
        val = df['Cold_Probability'].quantile(pct / 100)
        lines.append(f"| Top {100-pct}% | {val*100:.1f}% |")

    lines += [
        f"",
        f"---",
        f"",
        f"## What this means for the lab",
        f"",
        f"- The **top 15 candidates** are recommended starting points for expression and activity assays at 4–10 °C.",
        f"- **{n_high:,} proteins** ({frac_90:.1f}% of the proteome) exceed 90% cold-probability — the high-confidence pool.",
        f"- Wet-lab validation of top candidates will confirm cold-active enzymatic activity.",
        f"",
        f"---",
        f"",
        f"*Generated by PsychroScan — [github.com/yourusername/psychroscan](https://github.com/yourusername/psychroscan)*",
    ]
    return "\n".join(lines)


# ── PDF ───────────────────────────────────────────────────────────────────────
def build_pdf(organism, df, out_path):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                    Table, TableStyle, HRFlowable)
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
    from reportlab.pdfgen import canvas as pdfcanvas

    top15   = df.nlargest(15, 'Cold_Probability')
    ppi     = df['Cold_Probability'].nlargest(100).mean() * 100
    frac_90 = (df['Cold_Probability'] >= 0.90).mean() * 100
    n_high  = (df['Cold_Probability'] >= 0.90).sum()
    verdict, desc, v_color = interpret_ppi(ppi)
    org_display = organism.replace('_', ' ')

    C_COLD  = colors.HexColor(COLD)
    C_BLUE  = colors.HexColor(BLUE)
    C_LIGHT = colors.HexColor(LIGHT)
    C_GREEN = colors.HexColor(GREEN)
    C_GREY  = colors.HexColor(GREY)
    C_VERD  = colors.HexColor(v_color)
    C_WHITE = colors.white
    C_BG    = colors.HexColor("#f8f9fa")

    def S(name, **kw):
        return ParagraphStyle(name, **kw)

    styles = getSampleStyleSheet()
    TITLE  = S("t", fontSize=20, fontName="Helvetica-Bold",
               textColor=C_WHITE, leading=24)
    SUB    = S("s", fontSize=10, fontName="Helvetica",
               textColor=colors.HexColor("#aed6f1"), leading=13)
    SECT   = S("h", fontSize=12, fontName="Helvetica-Bold",
               textColor=C_COLD, spaceBefore=10, spaceAfter=4)
    BODY   = S("b", fontSize=9.5, fontName="Helvetica",
               textColor=colors.HexColor("#1c2833"), leading=14, alignment=TA_JUSTIFY)
    MONO   = S("m", fontSize=8.5, fontName="Courier",
               textColor=colors.HexColor("#2c3e50"), leading=12)
    VERD_S = S("v", fontSize=13, fontName="Helvetica-Bold",
               textColor=C_VERD, alignment=TA_CENTER, spaceAfter=4)
    VERD_D = S("vd", fontSize=9.5, fontName="Helvetica",
               textColor=colors.HexColor("#5d6d7e"), alignment=TA_CENTER)

    def header_footer(canvas, doc):
        W, H = A4
        canvas.saveState()
        canvas.setFillColor(C_COLD)
        canvas.rect(0, H - 3.8*cm, W, 3.8*cm, fill=1, stroke=0)
        canvas.setFillColor(C_BLUE)
        canvas.setLineWidth(3)
        canvas.line(0, H - 3.8*cm, W, H - 3.8*cm)
        canvas.setFillColor(C_WHITE)
        canvas.setFont("Helvetica-Bold", 18)
        canvas.drawString(1.8*cm, H - 1.8*cm, "PsychroScan")
        canvas.setFont("Helvetica", 9)
        canvas.setFillColor(colors.HexColor("#aed6f1"))
        canvas.drawString(1.8*cm, H - 2.4*cm,
                          f"Cold-Enzyme Bioprospecting Report   |   {org_display}")
        canvas.drawString(1.8*cm, H - 3.0*cm, f"Generated: {date.today()}")
        # PPI badge
        ppi_color = C_GREEN if ppi > 50 else colors.HexColor(WARN) if ppi > 30 else colors.HexColor("#c0392b")
        canvas.setFillColor(ppi_color)
        canvas.roundRect(W - 4.2*cm, H - 3.4*cm, 2.8*cm, 1.0*cm, 5, fill=1, stroke=0)
        canvas.setFillColor(C_WHITE)
        canvas.setFont("Helvetica-Bold", 16)
        canvas.drawCentredString(W - 2.8*cm, H - 2.7*cm, f"PPI {ppi:.0f}")
        canvas.setFont("Helvetica", 7.5)
        canvas.drawCentredString(W - 2.8*cm, H - 3.25*cm, "/ 100")
        # Footer
        canvas.setFillColor(C_COLD)
        canvas.rect(0, 0, W, 0.8*cm, fill=1, stroke=0)
        canvas.setFillColor(C_GREY)
        canvas.setFont("Helvetica", 7.5)
        canvas.drawCentredString(W/2, 0.28*cm,
            "PsychroScan v3  |  LightGBM + Optuna  |  AUC-ROC 0.9991  |  github.com/yourusername/psychroscan")
        canvas.restoreState()

    doc   = SimpleDocTemplate(out_path, pagesize=A4,
                              leftMargin=1.8*cm, rightMargin=1.8*cm,
                              topMargin=4.5*cm, bottomMargin=1.5*cm)
    W_IN  = A4[0] - 3.6*cm
    story = []

    # ── Verdict box ────────────────────────────────────────────────────────────
    verdict_data = [[Paragraph(verdict, VERD_S)], [Paragraph(desc, VERD_D)]]
    vt = Table(verdict_data, colWidths=[W_IN])
    vt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f0f0f0")),
        ('BOX', (0,0), (-1,-1), 1.5, C_VERD),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
    ]))
    story.append(vt)
    story.append(Spacer(1, 0.4*cm))

    # ── PPI metrics ────────────────────────────────────────────────────────────
    story.append(Paragraph("Psychrophilic Proteome Index", SECT))
    story.append(HRFlowable(width="100%", thickness=1, color=C_BLUE, spaceAfter=6))

    ppi_rows = [
        [Paragraph("<b>Metric</b>", BODY), Paragraph("<b>Value</b>", BODY)],
        [Paragraph("PPI score", BODY),     Paragraph(f"<b>{ppi:.1f} / 100</b>", BODY)],
        [Paragraph("Top-100 mean probability", BODY),
         Paragraph(f"{df['Cold_Probability'].nlargest(100).mean()*100:.1f}%", BODY)],
        [Paragraph("Fraction above 90% confidence", BODY),
         Paragraph(f"{frac_90:.1f}%  ({n_high:,} proteins)", BODY)],
        [Paragraph("Total proteins scored", BODY),
         Paragraph(f"{len(df):,}", BODY)],
    ]
    pt = Table(ppi_rows, colWidths=[W_IN*0.65, W_IN*0.35])
    pt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), C_COLD),
        ('TEXTCOLOR',  (0,0), (-1,0), C_WHITE),
        ('BACKGROUND', (0,1), (-1,1), C_LIGHT),
        ('BACKGROUND', (0,2), (-1,2), C_WHITE),
        ('BACKGROUND', (0,3), (-1,3), C_LIGHT),
        ('BACKGROUND', (0,4), (-1,4), C_WHITE),
        ('BOX', (0,0), (-1,-1), 0.5, C_BLUE),
        ('INNERGRID', (0,0), (-1,-1), 0.3, C_GREY),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(pt)
    story.append(Spacer(1, 0.4*cm))

    # ── Top 15 ─────────────────────────────────────────────────────────────────
    story.append(Paragraph("Top 15 Cold-Active Candidates", SECT))
    story.append(HRFlowable(width="100%", thickness=1, color=C_BLUE, spaceAfter=6))

    top_rows = [[
        Paragraph("<b>Rank</b>", BODY),
        Paragraph("<b>Protein ID</b>", BODY),
        Paragraph("<b>P(Cold)</b>", BODY),
        Paragraph("<b>Confidence</b>", BODY),
    ]]
    for i, (_, row) in enumerate(top15.iterrows(), 1):
        p   = row['Cold_Probability']
        bar = "█" * int(p * 15) + "░" * (15 - int(p * 15))
        top_rows.append([
            Paragraph(str(i), BODY),
            Paragraph(row['Protein_ID'], MONO),
            Paragraph(f"{p*100:.2f}%", BODY),
            Paragraph(bar, MONO),
        ])

    tt = Table(top_rows, colWidths=[W_IN*0.07, W_IN*0.42, W_IN*0.13, W_IN*0.38])
    ts_list = [
        ('BACKGROUND', (0,0), (-1,0), C_COLD),
        ('TEXTCOLOR',  (0,0), (-1,0), C_WHITE),
        ('BOX', (0,0), (-1,-1), 0.5, C_BLUE),
        ('INNERGRID', (0,0), (-1,-1), 0.3, C_GREY),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]
    for i in range(1, len(top_rows)):
        bg = C_LIGHT if i % 2 == 1 else C_WHITE
        ts_list.append(('BACKGROUND', (0,i), (-1,i), bg))
    tt.setStyle(TableStyle(ts_list))
    story.append(tt)

    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        "Search any Protein ID at <link href='https://www.uniprot.org/uniprotkb/'>UniProt</link> "
        "for functional annotation and literature references.",
        S("note", fontSize=8.5, fontName="Helvetica", textColor=C_GREY,
          leftIndent=6)))

    story.append(Spacer(1, 0.4*cm))

    # ── Lab interpretation ─────────────────────────────────────────────────────
    story.append(Paragraph("What this means for the lab", SECT))
    story.append(HRFlowable(width="100%", thickness=1, color=C_BLUE, spaceAfter=6))
    story.append(Paragraph(
        f"The <b>top 15 candidates</b> are the recommended starting points for "
        f"heterologous expression and enzymatic activity assays at 4-10 degC. "
        f"<b>{n_high:,} proteins</b> ({frac_90:.1f}% of the proteome) exceed the "
        f"90% confidence threshold, defining the high-confidence cold-active pool. "
        f"Wet-lab validation of these predictions will confirm cold-active "
        f"enzymatic activity and provide the experimental data required for "
        f"further characterisation.",
        BODY))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    print(f"  PDF: {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────────
def generate_report(organism, make_pdf=True):
    print(f"  Organism: {organism}")
    df = load_results(organism)

    md_path = os.path.join(REPORTS_DIR, f"{organism}_report.md")
    with open(md_path, 'w') as f:
        f.write(build_markdown(organism, df))
    print(f"  MD:  {md_path}")

    if make_pdf:
        pdf_path = os.path.join(REPORTS_DIR, f"{organism}_report.pdf")
        build_pdf(organism, df, pdf_path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--organism', type=str)
    parser.add_argument('--all',    action='store_true')
    parser.add_argument('--no-pdf', action='store_true')
    args = parser.parse_args()
    make_pdf = not args.no_pdf

    print("\n" + "="*55)
    print("  PsychroScan — Report Generator")
    print("="*55 + "\n")

    csvs = [f.replace('_full_results.csv', '')
            for f in os.listdir(GENOMES_DIR)
            if f.endswith('_full_results.csv')]

    if args.organism:
        generate_report(args.organism, make_pdf)
    elif args.all or not args.organism:
        if not csvs:
            print("  No results found. Run: python src/09_predict_new_genome.py")
            return
        for org in sorted(csvs):
            generate_report(org, make_pdf)

    print(f"\n  Reports saved to: {REPORTS_DIR}/\n")


if __name__ == "__main__":
    main()